# vi:syntax=yaml ft=yaml
# Project name
name: Craft3
# Project paths
# path on you computer, we like to commit the Vagrantfile and dependencies to the project repo.
local_path: ../
# path on the vagrant box
remote_path: /var/www/html
# Sites
sites:
    # site label, you can have unlimited sets of sites childern
    example:
        # this can also have a local path for the http conf
        docroot: /var/www/html/web
        domains:
            - local.craft3.com
        #boolean
        force_https: true
